### ISSUE TITLE
 no aging effect when train a ageslider on Stable Diffusion XL

### ISSUE THREAD

**Issue by cuixing100876** [rohitgandikota/sliders#60]
After training an ageslider on Stable Diffusion XL following instructions in the readme, the inference result has no aging effect. The results are pasted as follows:
(The provided checkpoint of ageslider in "https://sliders.baulab.info/weights/xl_sliders/" works properly.)
<img width="815" alt="image" src="https://github.com/rohitgandikota/sliders/assets/145273317/2d5971c1-e7f2-4a67-885d-242dd1247dec">

**Comment by rohitgandikota** [comment]
The provided checkpoints are disentangled across race and gender. 

Could you try with the prompts provided in the repo `textsliders/data/prompts-xl.yaml`? with attributes like - `white, black, asian, Indian, hispanic`

**Comment by trippedout** [comment]
ran into a similar issue when testing SD2.1 - could you provide some extra guidance on what exactly needs to change in the config.yaml besides the model_name and v2: true params? i changed nothing else 

what did you mean re: trying with the prompts in yaml? only one is uncommented currently with fresh pull

**Comment by rohitgandikota** [comment]
hi @trippedout - 
for SD2.1 I would use these configs:
```
pretrained_model:
  name_or_path: "stabilityai/stable-diffusion-2-1" # you can also use .ckpt or .safetensors models
  v2: true # true if model is v2.x
  v_pred: true # true if model uses v-prediction
```
Apart from this rest all should stay the same.

The original issue asks about age sliders. The current `textsliders/data/prompts-xl.yaml` file has prompts we used for our age slider. For SDXL sliders, turns out `--attributes` is very important for better directions. That refers to our disentanglement formulation. Hope this makes sense.
